# Default values for funcx_endpoint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
funcXServiceAddress: https://api2.funcx.org
image:
  repository: funcx/kube-endpoint
  tag: v0.3.0-3.7
  pullPolicy: Always

workerImage: python:3.6-buster
workerInit: pip install funcx-endpoint>=0.2.0
workerNamespace: default
logDir: /tmp/worker_logs

rbacEnabled: true
nameOverride: funcx-endpoint

initMem: 2000Mi
maxMem: 16000Mi
initCPU: 1
maxCPU: 2

initBlocks: 2
minBlocks: 2
maxBlocks: 2
maxWorkersPerPod: 1

detachEndpoint: true

endpointUUID: 4b116d3c-1703-4f8f-9f6f-39921e5864df
funcxSecret: funcx-sdk-tokens-ryan
