name: Push to PyPI

on:
  release:
    types: [released, prereleased]

jobs:
  publish-sdk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
    - name: Set the funcx version
      env:
        funcx_version: ${{ github.ref }}
      run: |
        echo "funcx_version $funcx_version"
        sed "s/__version__ *= *\".*\"/__version__ = \"$funcx_version\"/" funcx_sdk/funcx/sdk/version.py > funcx_sdk/funcx/sdk/version.py
        sed "s/__version__ *= *\".*\"/__version__ = \"$funcx_version\"/" funcx_endpoint/funcx_endpoint/version.py > funcx_endpoint/funcx_endpoint/version.py
      shell: bash -x

    - name: Push updated version to branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump version
    - name: Build the sdk
      run: |
        cd funcx_sdk
        python -m build --sdist --wheel
    - name: Build the endpoint
      run: |
        cd funcx_endpoint
        python -m build --sdist --wheel
