name: Push to PyPI

on:
  release:
    types: [released, prereleased]

jobs:
  publish-sdk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Git branch name
      id: git-branch-name
      uses: EthanSK/git-branch-name-action@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
    - name: Set the funcx version
      run: |
        echo "funcx_version $GIT_BRANCH_NAME"
        sed -i "s/__version__ *= *\".*\"/__version__ = \"$GIT_BRANCH_NAME\"/" funcx_sdk/funcx/sdk/version.py
        sed -i "s/__version__ *= *\".*\"/__version__ = \"$GIT_BRANCH_NAME\"/" funcx_endpoint/funcx_endpoint/version.py
    - name: Push updated version to branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump version
    - name: Build the sdk
      run: |
        cd funcx_sdk
        cat funcx/sdk/version.py
        python -m build --sdist --wheel
    - name: Build the endpoint
      run: |
        cd funcx_endpoint
        python -m build --sdist --wheel
